/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as BookBookshelfIdRouteImport } from './routes/book.$bookshelfId'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppConfigRouteImport } from './routes/_app/config'
import { Route as AppBookDetailRouteImport } from './routes/_app/book-detail'
import { Route as AppSourcesIndexRouteImport } from './routes/_app/sources/index'
import { Route as ReadBookshelfIdChapterIndexRouteImport } from './routes/read.$bookshelfId.$chapterIndex'
import { Route as AppSourcesNewRouteImport } from './routes/_app/sources/new'
import { Route as AppSourcesSourceIdRouteImport } from './routes/_app/sources/$sourceId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const BookBookshelfIdRoute = BookBookshelfIdRouteImport.update({
  id: '/book/$bookshelfId',
  path: '/book/$bookshelfId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRoute,
} as any)
const AppBookDetailRoute = AppBookDetailRouteImport.update({
  id: '/book-detail',
  path: '/book-detail',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesIndexRoute = AppSourcesIndexRouteImport.update({
  id: '/sources/',
  path: '/sources/',
  getParentRoute: () => AppRoute,
} as any)
const ReadBookshelfIdChapterIndexRoute =
  ReadBookshelfIdChapterIndexRouteImport.update({
    id: '/read/$bookshelfId/$chapterIndex',
    path: '/read/$bookshelfId/$chapterIndex',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSourcesNewRoute = AppSourcesNewRouteImport.update({
  id: '/sources/new',
  path: '/sources/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcesSourceIdRoute = AppSourcesSourceIdRouteImport.update({
  id: '/sources/$sourceId',
  path: '/sources/$sourceId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/book-detail': typeof AppBookDetailRoute
  '/config': typeof AppConfigRoute
  '/search': typeof AppSearchRoute
  '/api/$': typeof ApiSplatRoute
  '/book/$bookshelfId': typeof BookBookshelfIdRoute
  '/sources/$sourceId': typeof AppSourcesSourceIdRoute
  '/sources/new': typeof AppSourcesNewRoute
  '/read/$bookshelfId/$chapterIndex': typeof ReadBookshelfIdChapterIndexRoute
  '/sources/': typeof AppSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/book-detail': typeof AppBookDetailRoute
  '/config': typeof AppConfigRoute
  '/search': typeof AppSearchRoute
  '/api/$': typeof ApiSplatRoute
  '/book/$bookshelfId': typeof BookBookshelfIdRoute
  '/': typeof AppIndexRoute
  '/sources/$sourceId': typeof AppSourcesSourceIdRoute
  '/sources/new': typeof AppSourcesNewRoute
  '/read/$bookshelfId/$chapterIndex': typeof ReadBookshelfIdChapterIndexRoute
  '/sources': typeof AppSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/book-detail': typeof AppBookDetailRoute
  '/_app/config': typeof AppConfigRoute
  '/_app/search': typeof AppSearchRoute
  '/api/$': typeof ApiSplatRoute
  '/book/$bookshelfId': typeof BookBookshelfIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/sources/$sourceId': typeof AppSourcesSourceIdRoute
  '/_app/sources/new': typeof AppSourcesNewRoute
  '/read/$bookshelfId/$chapterIndex': typeof ReadBookshelfIdChapterIndexRoute
  '/_app/sources/': typeof AppSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-detail'
    | '/config'
    | '/search'
    | '/api/$'
    | '/book/$bookshelfId'
    | '/sources/$sourceId'
    | '/sources/new'
    | '/read/$bookshelfId/$chapterIndex'
    | '/sources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/book-detail'
    | '/config'
    | '/search'
    | '/api/$'
    | '/book/$bookshelfId'
    | '/'
    | '/sources/$sourceId'
    | '/sources/new'
    | '/read/$bookshelfId/$chapterIndex'
    | '/sources'
  id:
    | '__root__'
    | '/_app'
    | '/_app/book-detail'
    | '/_app/config'
    | '/_app/search'
    | '/api/$'
    | '/book/$bookshelfId'
    | '/_app/'
    | '/_app/sources/$sourceId'
    | '/_app/sources/new'
    | '/read/$bookshelfId/$chapterIndex'
    | '/_app/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  BookBookshelfIdRoute: typeof BookBookshelfIdRoute
  ReadBookshelfIdChapterIndexRoute: typeof ReadBookshelfIdChapterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/$bookshelfId': {
      id: '/book/$bookshelfId'
      path: '/book/$bookshelfId'
      fullPath: '/book/$bookshelfId'
      preLoaderRoute: typeof BookBookshelfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/config': {
      id: '/_app/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book-detail': {
      id: '/_app/book-detail'
      path: '/book-detail'
      fullPath: '/book-detail'
      preLoaderRoute: typeof AppBookDetailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/': {
      id: '/_app/sources/'
      path: '/sources'
      fullPath: '/sources/'
      preLoaderRoute: typeof AppSourcesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/read/$bookshelfId/$chapterIndex': {
      id: '/read/$bookshelfId/$chapterIndex'
      path: '/read/$bookshelfId/$chapterIndex'
      fullPath: '/read/$bookshelfId/$chapterIndex'
      preLoaderRoute: typeof ReadBookshelfIdChapterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sources/new': {
      id: '/_app/sources/new'
      path: '/sources/new'
      fullPath: '/sources/new'
      preLoaderRoute: typeof AppSourcesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sources/$sourceId': {
      id: '/_app/sources/$sourceId'
      path: '/sources/$sourceId'
      fullPath: '/sources/$sourceId'
      preLoaderRoute: typeof AppSourcesSourceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBookDetailRoute: typeof AppBookDetailRoute
  AppConfigRoute: typeof AppConfigRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSourcesSourceIdRoute: typeof AppSourcesSourceIdRoute
  AppSourcesNewRoute: typeof AppSourcesNewRoute
  AppSourcesIndexRoute: typeof AppSourcesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookDetailRoute: AppBookDetailRoute,
  AppConfigRoute: AppConfigRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppSourcesSourceIdRoute: AppSourcesSourceIdRoute,
  AppSourcesNewRoute: AppSourcesNewRoute,
  AppSourcesIndexRoute: AppSourcesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  BookBookshelfIdRoute: BookBookshelfIdRoute,
  ReadBookshelfIdChapterIndexRoute: ReadBookshelfIdChapterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
